name: Frontend Test With Node
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # node_modulesのあるディレクトリに移動してください
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      #　node_modulesのあるディレクトリに移動してください
      - name: Run lint
        run: |
          cd frontend
          npm run lint

      #　node_modulesのあるディレクトリに移動してください
      - name: Run Jest tests
        run: |
          cd frontend
          npm run test
