name: Custom Actions Test
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.PAT }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Custom Actions
        uses: o-ga09/zibun-releaser@v0.0.15
        with:
          release-version: 'v999.999.999'
          github-token: ${{ secrets.PAT }}
          filepath: "CHANGELOG.md"
          apikey: ${{ secrets.APIKEY }}
