name: Custom Actions Test
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Custom Actions
        uses: o-ga09/zibun-releaser@v0.0.6
        with:
          release-version: 'v1.0.0'
          github-token: ${{ secrets.PAT }}
          filepath: "CHANGELOG.md"
          apikey: ${{ secrets.APIKEY }}
