##########################
# secrets変数に設定すること
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_REGION
#########################
name: AWS deploy

on:
  push:
    paths:
      - "backend/**.go"
      - "frontend/**/*.ts"
      - "frontend/**/*.tsx"
    branches:
      - main
jobs:
  golang-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: testing
        run: |
          cd packages/functions
          go test ./... -coverprofile=coverage.out

      - name: create report
        uses: k1LoW/octocov-action@v0

  svelte-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd packages/frontend
          npm install

      - name: Run Jest tests
        run: |
          cd packages/frontend
          npm run test
  deploy:
    needs:
      - golang-test
      - svelte-test
    if: ${{ needs.golang-test.result == 'success' && needs.svelte-test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-python@v3

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependecies
        run: |
          npm install

      - name: Deploy
        run: npm run deploy
