name: Tag Release
on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Release"
        run: echo "Release"

      - name: "tag Release"
        if: ${{ startsWith(github.ref, 'refs/tags/') }} = false
        run: |
          echo "Release"
