name: Tag Release
on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Release"
        run: echo "Release"

      - name: "tag Release"
        run: |
          if [ "${{ startsWith(github.ref, 'refs/tags/') }}" = "true" ]; then
            echo "【PROD】This is tag push. Continue with your steps."
          fi
